services:
  php:
    build: .
    restart: always
    ports:
      - "9200:80" # HTTP
      - "9201:443" # HTTPS
      - "9201:443/udp" # HTTP/3
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "photo-gallery.zak.dev=127.0.0.1"
      - "photo-gallery.zak.dev=::1"

volumes:
  caddy_data:
  caddy_config:
